language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 5.x
solution: RediSearchCore.sln
before_install:
  - docker pull redislabs/redisearch:latest
  - docker run -d -p 6379:6379 redislabs/redisearch:latest
script:
  - dotnet restore
  - dotnet build
  - dotnet test RediSearchCore.Tests/RediSearchCore.Tests.csproj
on:
  tags: true