name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup RediSearch
      uses: caiomarruda/redisearch-action@v1.0.1
    - uses: actions/checkout@v1
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build with dotnet
      run: |
        dotnet build --configuration Release
        dotnet test RediSearchCore.Tests/RediSearchCore.Tests.csproj
